# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ms_service_pb2 as ms__service__pb2


class MSServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Predict = channel.unary_unary(
        '/ms_serving.MSService/Predict',
        request_serializer=ms__service__pb2.PredictRequest.SerializeToString,
        response_deserializer=ms__service__pb2.PredictReply.FromString,
        )
    self.Test = channel.unary_unary(
        '/ms_serving.MSService/Test',
        request_serializer=ms__service__pb2.PredictRequest.SerializeToString,
        response_deserializer=ms__service__pb2.PredictReply.FromString,
        )


class MSServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Predict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Test(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MSServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Predict': grpc.unary_unary_rpc_method_handler(
          servicer.Predict,
          request_deserializer=ms__service__pb2.PredictRequest.FromString,
          response_serializer=ms__service__pb2.PredictReply.SerializeToString,
      ),
      'Test': grpc.unary_unary_rpc_method_handler(
          servicer.Test,
          request_deserializer=ms__service__pb2.PredictRequest.FromString,
          response_serializer=ms__service__pb2.PredictReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ms_serving.MSService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
