seed: 42
output_dir: './output'
load_checkpoint: '/path/to/Qwen2.5-7B/'
load_ckpt_format: 'safetensors'
auto_trans_ckpt: True  # If true, auto transform load_checkpoint to load in distributed model
only_save_strategy: False
resume_training: False
run_mode: 'finetune'

# trainer config
trainer:
  type: CausalLanguageModelingTrainer
  model_name: 'qwen2_5_7b'

# runner config
runner_config:
  epochs: 2
  batch_size: 1
  sink_mode: True
  sink_size: 1

# wrapper cell config
runner_wrapper:
  type: MFTrainOneStepCell
  scale_sense:
    type: DynamicLossScaleUpdateCell
    loss_scale_value: 4096
    scale_factor: 1
    scale_window: 100000
  use_clip_grad: True
  max_grad_norm: 1.0

# optimizer
optimizer:
  type: AdamW
  betas: [0.9, 0.95]
  eps: 1.e-8
  learning_rate: 1.e-6
  weight_decay: 0.01

# lr schedule
lr_schedule:
  type: CosineWithWarmUpLR
  learning_rate: 1.e-6
  lr_end: 1.e-6
  warmup_ratio: 0
  total_steps: -1 # -1 means it will load the total steps of the dataset

# dataset
train_dataset: &train_dataset
  input_columns: &input_columns ["input_ids", "labels", "loss_mask", "position_ids", "attention_mask"]
  construct_args_key: *input_columns
  data_loader:
    type: CommonDataLoader
    load_func: 'load_dataset'
    shuffle: False
    path: "llm-wizard/alpaca-gpt4-data"
    packing: pack
    handler:
      - type: AlpacaInstructDataHandler
        tokenizer:
          vocab_file: "/path/to/Qwen2.5-7B/vocab.json"
          merges_file: "/path/to/Qwen2.5-7B/merges.txt"
          unk_token: null
          pad_token: "<|endoftext|>"
          eos_token: "<|im_end|>"
          bos_token: null
          type: Qwen2Tokenizer
          auto_register: qwen2_5_tokenizer.Qwen2Tokenizer
        seq_length: &seq_length 8192
        prompt_key: "conversations"
        output_columns: ["input_ids", "labels"]
        is_dynamic: False
      - type: PackingHandler
        seq_length: *seq_length
        output_columns: ["input_ids", "labels", "actual_seq_len"]
    adaptor_config:
      compress_mask: False
    column_names: *input_columns
  python_multiprocessing: False
  drop_remainder: True
  numa_enable: False
  prefetch_size: 1
train_dataset_task:
  type: CausalLanguageModelDataset
  dataset_config: *train_dataset

use_parallel: True
# parallel context config
parallel:
  parallel_mode: 1 # 0-data parallel, 1-semi-auto parallel, 2-auto parallel, 3-hybrid parallel
  gradients_mean: False
  enable_alltoall: False
  full_batch: True
  search_mode: "sharding_propagation"
  strategy_ckpt_save_file: "./ckpt_strategy.ckpt"
  enable_parallel_optimizer: True
  parallel_optimizer_config:
    gradient_accumulation_shard: False
    parallel_optimizer_threshold: 64

# default parallel of device num = 8
parallel_config:
  data_parallel: 4
  model_parallel: 1
  pipeline_stage: 2
  context_parallel: 1
  use_seq_parallel: True
  micro_batch_num: 16
  vocab_emb_dp: False
  gradient_aggregation_group: 4
# when model parallel is greater than 1, we can set micro_batch_interleave_num=2, that may accelerate the train process.
micro_batch_interleave_num: 1

# recompute config
recompute_config:
  recompute: False
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: False
  recompute_slice_activation: False

# callbacks
callbacks:
  - type: MFLossMonitor
  - type: CheckpointMonitor
    prefix: "qwen2_5"
    save_checkpoint_steps: 5000
    keep_checkpoint_max: 1
    integrated_save: False
    async_save: False
    checkpoint_format: "safetensors"

# mindspore context init config
context:
  mode: 0 #0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  max_call_depth: 10000
  max_device_memory: "58GB"
  save_graphs: False
  save_graphs_path: "./graph"
  device_id: 0
  memory_optimize_level: "O1"
  jit_config:
    jit_level: "O1"
  ascend_config:
    precision_mode: "must_keep_origin_dtype"

# model config
model:
  model_config:
    type: LlamaConfig
    batch_size: 1
    seq_length: *seq_length
    hidden_size: 3584
    num_layers: 4
    num_heads: 28
    n_kv_heads: 4
    vocab_size: 152064
    intermediate_size: 18944
    qkv_has_bias: True
    rms_norm_eps: 1.0e-6
    theta: 1000000.0
    max_position_embedding: 131072
    emb_dropout_prob: 0.0
    eos_token_id: 151643
    pad_token_id: 151643
    bos_token_id: 151643
    compute_dtype: "bfloat16"
    layernorm_compute_type: "float32"
    softmax_compute_type: "float32"
    rotary_dtype: "float32"
    param_init_type: "float32"
    use_past: False
    use_flash_attention: True
    use_past_shard: False
    offset: 0
    checkpoint_name_or_path: ""
    repetition_penalty: 1.05
    max_decode_length: 1024
    top_k: 0
    top_p: 0.8
    do_sample: False
    extend_method: "None" # support "None", "PI", "NTK"
    fine_grain_interleave: 1
    qkv_concat: false
    # configuration items copied from Qwen
    rotary_pct: 1.0
    rotary_emb_base: 1000000
    input_sliced_sig: True
  arch:
    type: LlamaForCausalLM

profile: False
profile_start_step: 1
profile_stop_step: 10
init_start_profile: False
profile_communication: False
profile_memory: True
layer_scale: False
layer_decay: 0.65
lr_scale_factor: 256
